# Generated by Django 2.2.28 on 2023-01-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holonet', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holonetuser',
            name='about',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
